version: '{build}'
os: Visual Studio 2015
configuration: Release
platform: Any CPU
skip_tags: true
before_build:
- ps: >-
    git lfs pull
    nuget restore
build:
  project: Scallion.sln
  verbosity: minimal
